### ISSUE TITLE
[feature] DevOps/GitHub Actions Release Pipeline Guidance

### ISSUE THREAD

**Issue by klawrawkz** [Azure/caf-terraform-landingzones#28]
**Is your feature request related to a problem? Please describe.**

There are sporadic mentions of benefits of the CAF rover in DevOps, but there is no guidance on configuration of such in Azure DevOps or in GitHub via "actions."

**Describe the solution you'd like**

I'm more than happy to contribute to this effort, as I believe this project has the potential to dramatically improve our ability to produce, release, maintain standards-based IaC.  Perhaps I can be involved in the capacity of **_guinea pig,_** and apply instructions and guidance in DevOps implementation approach to validate the concept. I can create accompanying documentation for other developers/implementers of the project. I'll gladly produce the technical documentation for publication here in return for assistance with the DevOps pipelines.

**Describe alternatives you've considered**

I've considered _"hacking it together"_ and getting it to run in my DevOps environment.  I think going through the process, and documenting the approach for the general public is a better more valuable option.

**Additional context**

**Comment by arnaudlh** [comment]
Good feedback @klawrawkz we will add this for 2004 release.

**Comment by Masahigo** [comment]
@arnaudlh Hi, I was testing running the Rover image from Azure DevOps container job using a _Hosted agent_. I was basically trying to mimic what works in Github action example: https://github.com/aztfmod/rover/blob/master/.github/workflows/ci-branches.yml#L63

This is what my **azure-pipelines.yml** looks like so far

```yml
variables:
  location: 'westeurope'

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

container: aztfmod/rover:2004.1606

steps:
- script: |
    az login --service-principal -u '$(ARM_CLIENT_ID)' -p '$(ARM_CLIENT_SECRET)' --tenant '$(ARM_TENANT_ID)'
    az account set -s  $(ARM_SUBSCRIPTION_ID)
    echo "local user: $(whoami)"
  displayName: 'Login to Azure'
```

The hosted agent OS (vm image) should be same as in Github action example (ubuntu-18.04).

_However, the pipeline fails already in container initialization phase:_

![image](https://user-images.githubusercontent.com/9364649/80379731-2763f680-88a7-11ea-92c6-a171206c84b7.png)

Are you planning to support ADO Hosted agents (container jobs) in the future or is it possible to get it working somehow like this? Was hoping to survive without self-hosted agents at this point but would be valuable to know if they're the only way to go if using Azure DevOps for CI/CD.

**Comment by arnaudlh** [comment]
hi folks, we are going to publish guidance on that in a couple of days, with a brand new version of rover to support those scenarios. Bear with us :)

**Comment by Masahigo** [comment]
> Are you planning to support ADO Hosted agents (container jobs) in the future or is it possible to get it working somehow like this?

@arnaudlh Seems to work after all, was just missing this additional options from the container job

```
container:
  image: aztfmod/rover:2004.1606
  options: --user 0
```

**Comment by Masahigo** [comment]
I managed to get around this limitation with ADO hosted agents, by installing `sudo` to the Rover container in following way

```yml

..
container:
  image: aztfmod/rover:2004.1606
  options: --user 0 --name rover-container -v /usr/bin/docker:/tmp/docker:ro
..

steps:
- script: |
    /tmp/docker exec -t -u 0 rover-container \
    sh -c "yum install -y sudo"
  displayName: 'Set up sudo'
- script: |
    ls -la
    sudo chmod -R 777 /home/vscode
    sudo chmod -R 777 /tf/launchpads
  displayName: 'File permissions'
..

```

I had to elevate some file permissions this way. This is MVP but worked for me.
