### ISSUE TITLE
ASVM uses wrong platform firewall as DNS Server

### ISSUE THREAD

**Issue by arne21a** [Azure/caf-terraform-landingzones#346]
**Describe the bug**
i am currently working with caf asvm introduced by landingzones march release.
So im using the march platform templates in combination with march orion asvm tempalte.

The asvm template contains this block
```
      virtual_networks:
        vnet:
          name: {{landingzone_definition}}-{{env}}
          resource_group_key: networking
          region_key: region1
          dns_servers_keys:
            fw_secure_{{platform_mappings[env]}}:
              resource_type: azurerm_firewall
              lz_key: connectivity_secure_firewalls_{{platform_mappings[env]}}
              key: fw_secure_{{platform_mappings[env]}}
          address_space:
            - 10.101.8.0/23
```
this snippet is connecting the wrong firewall to the DNS config of the VNet.

**Expected behavior**

March platform release deploys two firewalls:
Hub attached firewall ```connectivity_secure_firewalls_env```
VNet attached firewall as a central DNS instance ```connectivity_private_dns_firewalls_env```

I would expect the connectivity_private_dns_firewalls_env to be the DNS Server for the vnet

**Configuration (please complete the following information):**
 - OS and version: MacOS 11.6
 - Version of the rover: aztfmod/rover-preview:1.1.3-2201.190325
 - Version of the landing zone: 2203.1
